### ISSUE TITLE
Coplanarity condition does not work

### ISSUE THREAD

**Issue by protw** [DzReal/8-point-algorithm-MATLAB#3]
Dear Frederic, 

thank you very much for very neat and clear code of 8-point-algorithm.

In this connection I've got a couple of questions:
1. Trying to validate the veracity of the result applying the coplanarity condition `x1(i,:)*eMatrix8*x2(i,:)'` I obtain values far from zero. What is wrong? How can I build the coplanarity condition correctly?
2. I seem to have managed to adapt your code for spherical panoramas - a matrix built directly, and using the 8-point algorithm match each other. But I am not completely sure. My hesitation is elevated by fact the coplanarity condition does not work (see p. 1). Could you share by chance your code adapted for spherical panoramas?

Thank you in advance
Olegh

**Comment by fredzzhang** [comment]
Hi, Olegh 

Thanks for taking interest. This was part of my undergraduate project a long time ago...sorry I don't remember much of it now. I only tested the code on synthetic data. And someone pointed out before that the code seems to produce incorrect results on real data because the normalisation has some flaws.

Sorry I won't be able to solve your problems.

Fred

**Comment by protw** [comment]
Frederic, anyway thanks for the live response.
Olegh Bondarenko
<http://bit.ly/OleghBond>https://bit.ly/oleghbond





ср, 17 лют. 2021 о 03:51 Frederic Zhang <notifications@github.com> пише:
